# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef0f41361bff8e76eb2bce6aafd501e4b47d86703814c1f749a3e94ead9aa97b5a9d8508c7f77ced9f1d101b7ef44acfa880f6621b23fe778e67757d28697f7

test:
  secret_key_base: ea4bf9a793197c3f303c7f8c000704dada0113f7475c48d3111bfd363ba29733cf6a05c8f33ab855fcf6fc39fdcb903e5735eb9f8d42be3c0947c1bb2d2ab8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
